# Generated by Django 3.1.3 on 2021-09-19 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210919_0859'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiment',
            name='code',
            field=models.CharField(default='ABCDEF', editable=False, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='title',
            field=models.CharField(default='intonation-trainer', max_length=255, unique=True),
        ),
    ]
