# Generated by Django 3.1.3 on 2021-09-21 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210920_1109'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.URLField(null=True)),
                ('sentence', models.TextField()),
                ('intonation', models.CharField(max_length=255)),
                ('pitch', models.JSONField(null=True)),
                ('prominent_words', models.JSONField(null=True)),
                ('task', models.ManyToManyField(to='api.Tasks')),
            ],
        ),
    ]
