# Generated by Django 3.1.3 on 2021-09-22 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_sentence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responses',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='config',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
