# Generated by Django 3.1.3 on 2021-09-22 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20210922_0243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responses',
            name='data',
        ),
    ]
