# Generated by Django 3.1.3 on 2021-09-22 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_responses_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sentence',
            name='task',
        ),
        migrations.AddField(
            model_name='tasks',
            name='task',
            field=models.ManyToManyField(blank=True, to='api.Sentence'),
        ),
        migrations.AlterField(
            model_name='sentence',
            name='prominent_words',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
