# Generated by Django 3.1.3 on 2021-09-22 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20210922_0430'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence', models.ManyToManyField(blank=True, to='api.Sentence')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.tasks')),
            ],
        ),
    ]
