# Generated by Django 3.1.3 on 2021-09-22 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_trial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trial',
            name='correct_sentence_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='trial',
            name='target_field',
            field=models.CharField(choices=[('intonation', 'Intonation'), ('prominent_words', 'Prominent words'), ('id', 'Prominence')], max_length=25, null=True),
        ),
    ]
