# Generated by Django 3.1.3 on 2021-09-22 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20210922_0513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='task',
        ),
    ]
