# Generated by Django 3.1.3 on 2021-09-22 05:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0017_auto_20210922_0530'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Activities',
            new_name='Action',
        ),
        migrations.RenameModel(
            old_name='Tasks',
            new_name='Task',
        ),
        migrations.RenameModel(
            old_name='Responses',
            new_name='UserResponse',
        ),
    ]
