# Generated by Django 3.1.3 on 2021-09-22 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20210922_0537'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trial',
            old_name='sentence',
            new_name='sentences',
        ),
        migrations.RemoveField(
            model_name='trial',
            name='correct_sentence_id',
        ),
        migrations.AddField(
            model_name='trial',
            name='target_sentence',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='correct_sentence', to='api.sentence'),
        ),
    ]
