# Generated by Django 3.1.3 on 2021-09-22 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_task_instructions_short'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='example_sentence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.sentence'),
        ),
    ]
