# Generated by Django 3.1.3 on 2021-09-22 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20210922_0655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trial',
            name='target_field',
            field=models.CharField(blank=True, choices=[('intonation', 'Intonation'), ('prominent_words', 'Prominent words'), ('id', 'Prominence')], max_length=25, null=True),
        ),
    ]
