# Generated by Django 3.1.3 on 2021-09-22 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20210922_0713'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userresponse',
            name='task',
        ),
        migrations.AddField(
            model_name='userresponse',
            name='trial',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.trial'),
        ),
    ]
