# Generated by Django 3.1.3 on 2021-09-22 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_auto_20210922_1950'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sentence',
            old_name='audio',
            new_name='filepath',
        ),
    ]
