# Generated by Django 3.1.3 on 2021-09-22 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_auto_20210922_1951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userresponse',
            name='notes',
        ),
        migrations.AddField(
            model_name='userresponse',
            name='is_correct',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userresponse',
            name='response',
            field=models.JSONField(null=True),
        ),
    ]
